name: Deploy to Oracle Container Registry

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

      - name: Log into OCI
        id: login-oci
        run: |
          docker login iad.ocir.io --username='idzcwuebajei/hxexx2@gmail.com' --password='84.E+#5d6n6]Ple3PH_q'

      - name: Build, Tag and Push Image
        id: build-tag-and-push-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform=linux/amd64 -t "iad.ocir.io/idzcwuebajei/chumaengi-container-repo:$IMAGE_TAG" -f ./Dockerfile .
          docker push "iad.ocir.io/idzcwuebajei/chumaengi-container-repo:$IMAGE_TAG"
