name: Deploy to Oracle Container Registry

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Log into OCI
        id: login-oci
        run: |
          docker login iad.ocir.io --username='idzcwuebajei/hxexx2@gmail.com' --password='84.E+#5d6n6]Ple3PH_q'

      - name: Build, Tag and Push Image
        id: build-tag-and-push-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker buildx build --platform=linux/amd64 -t "iad.ocir.io/idzcwuebajei/chumaengi-container-repo:$IMAGE_TAG" .
          docker push "iad.ocir.io/idzcwuebajei/chumaengi-container-repo:$IMAGE_TAG"
